name: Build WDA IPA

on:
  workflow_dispatch: # Chạy thủ công

jobs:
  build:
    runs-on: macos-15 # Sử dụng runner mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Nâng cấp lên v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0' # Xcode 16 cho macOS 15

      - name: Build WebDriverAgent
        run: |
          mkdir build
          xcodebuild -project WebDriverAgent.xcodeproj \
                     -scheme WebDriverAgentRunner \
                     -destination 'generic/platform=iOS' \
                     -configuration Release \
                     -derivedDataPath build \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WebDriverAgent.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Nâng cấp lên v4 - Quan trọng nhất
        with:
          name: WebDriverAgent-IPA
          path: WebDriverAgent.ipa
